### ISSUE TITLE
ask about 100?

### ISSUE THREAD

**Issue by alfaruqrizqi18** [dancamdev/effectively_scale_UI_according_to_different_screen_sizes#1]
hi, can I ask what is 100?
`blockSizeHorizontal = screenWidth / 100;`

**Comment by dancamdev** [comment]
Hi, since we’re building our layout based on a grid, the line you mentioned defines a “Block”, or if you prefer, a cell of that grid. I devices to divide the screenWidth by 100 so that the horizontal block is exactly 1% of the horizontal space. So that when in the code I call ‘blockSizeHorizontal * 30’ it’s because I want that widget to use 30% of the available horizontal space. 

I’m closing this, because this is not actually an issue, hit me up on twitter at @dancamdev for any further question.
